name: Check and Sort Streams

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

# 添加权限设置
permissions:
  contents: write

jobs:
  check-streams:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python -m pip install --upgrade pip
        pip install requests aiohttp pyyaml
    
    - name: Run stream checker
      run: python src/check_streams.py
    
    - name: Sort valid streams
      run: python src/sort_streams.py
    
    - name: Configure Git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    
    - name: Commit and Push
      run: |
        # 获取最新更改
        git pull --rebase origin main
        
        # 添加更改
        git add -f data/valid_streams.txt
        git add -f data/sorted_streams.txt
        
        # 提交
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update stream lists"
          git push origin HEAD:main 