name: Check and Sort Streams

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

# 添加权限设置
permissions:
  contents: write

jobs:
  check-streams:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests aiohttp
    
    - name: Run stream checker
      run: python src/check_streams.py
    
    - name: Sort valid streams
      run: python src/sort_streams.py
    
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f data/valid_streams.txt
        git add -f data/sorted_streams.txt
        git commit -m "Update stream lists" || echo "No changes to commit"
        git push 